version: "3"

services:

  server:

    build: flask_crud/

    command: crud.py

    ports:
      - 5000:5000

  client:

    build: vue_client/
 
    command: npm run serve

    ports:
      - 8080:8080
